### ISSUE TITLE
Inconsistent deposit box state for shared drafts

### ISSUE THREAD

**Issue by max-moser** [tu-graz-library/invenio-curations#15]
This is very likely a permissions issue, where people who have been granted access to "edit" a draft get a weird state in the deposit box on the right.
It looks like the `RequestOrPublishButton` will only show the "Start publication process" button for people who have access to the draft but are not the owner.
This is likely because they don't have permissions to view the request.

Owner of the draft:
![image](https://github.com/user-attachments/assets/da1251c3-5f7b-4137-b161-1b3e3b2e5c19)

Person who the draft was shared with:
![image](https://github.com/user-attachments/assets/72058446-da09-41f4-b215-245c43e064cf)

Perhaps the button should not be rendered at all in this case?
After all, the "share" button isn't rendered either.

**Comment by max-moser** [comment]
Also note that clicking the "start publication process" button as the non-owner doesn't seemingly do anything on the deposit form.

**Comment by rekt-hard** [comment]
Related to #25
